### ISSUE TITLE
Remove Result

### ISSUE THREAD

**Issue by CodaFi** [typelift/Swiftx#18]
With Swift 2.0 introducing exceptions to take the place of `NSErrorPointer`-style functions, and the advent of `ErrorType`, Result's days are numbered.  I propose we remove it entirely, as it can be replicated with `Either<ErrorType, B>`.

**Comment by pthariensflame** [comment]
:+1:

**Comment by CodaFi** [comment]
This also frees up the `!!` operator for future evil.
