### ISSUE TITLE
Mention the included `SwiftCheck` dependency in `Readme.md`

### ISSUE THREAD

**Issue by DanielAsher** [typelift/Swiftx#34]
`SwiftCheck` is brilliant. Congratulations!

I discovered it, almost by accident, and it's just what the doctor ordered :+1: 

regards,
Daniel

**Comment by CodaFi** [comment]
I've been meaning to do something more general than that and create a repository that serves as a "master README" with brief summaries of each framework and a TypeLift-specific bug tracker/bulletin board.

**Comment by DanielAsher** [comment]
@CodaFi is there a slack.com team or other live venue for discussing typelift's frameworks? Or do you prefer working through github?

**Comment by CodaFi** [comment]
We haven't set anything up yet, so no.  For now it's all GH and Twitter.

**Comment by DanielAsher** [comment]
an alternative to a bespoke slack team, which only take 2 mins to set, would be:
https://functionalprogramming.slack.com/messages/swift/

**Comment by DanielAsher** [comment]
https://typelift.slack.com is available :)

**Comment by CodaFi** [comment]
Taken!

**Comment by DanielAsher** [comment]
Yikes. My checking whether it was free obviously was a bad move. I've still got the web page open. Should I close the web page? (and we'll cross our fingers :)
Or should I proceed and transfer ownership?

I've closed down the page, though the address may be held for a couple of mins. Let me know if you want me to proceed though...

**Comment by CodaFi** [comment]
I probably should have been more specific: I just signed up and took it myself.

**Comment by DanielAsher** [comment]
Brill! Well done.

Think I'll get myself an invite :)

**Comment by DanielAsher** [comment]
from slack.com:

> Allowing email signup
> 
> If email signup is enabled for your team, new members will be able to create an account on their own. 
> Team Owners can manage this option under Team Sign Up Mode on the Team Settings page.

**Comment by CodaFi** [comment]
I know.  I wish slack would allow public domains, so it's invite only unles you have another suggestion (I'm not entirely familiar with how this works anyways).

**Comment by DanielAsher** [comment]
pretty simple. You enable email signup from Team Settings page and then you'll get a email from slack when a user sign's up.

**Comment by CodaFi** [comment]
Which domains?

**Comment by DanielAsher** [comment]
~~typelift.slack.com, if I understand your question...~~

I need to research this too!

**Comment by pthariensflame** [comment]
@CodaFi Signing myself up now…

EDIT:  It looks like you need to send me an invite.  :(

**Comment by CodaFi** [comment]
Then it may just be best to stick to GH for now.  We're not big enough as an organization to warrant a full-scale chat yet.  Just open issues and we'll chat in there.

**Comment by CodaFi** [comment]
If you want an invite just shoot me an email (devteam DOT codafi over in gmail land).

**Comment by DanielAsher** [comment]
looks like this hack is the solution:

https://github.com/outsideris/slack-invite-automation

**Comment by CodaFi** [comment]
Closing this due to lack of action.

Thank you for raising the issue.  Hopefully we'll become big enough one day to warrant this kind of thing.
