### ISSUE TITLE
Podspec Update To Latest Version

### ISSUE THREAD

**Issue by AlexTanabe** [typelift/Swiftx#62]
Hi!

I am migrating my project to Swift 3 and was looking forward to use your newest Swift 3 version of SwiftX. However, after checking your Podspec, it seems that it hasn't been updated and is still in version 0.4, which prevents using your latest version.

Could you please update it?

Thanks in advance!

**Comment by CodaFi** [comment]
0.5.2 was just pushed to trunk.
